from enum import StrEnum


class ExecucaoStatus(StrEnum):
    PENDENTE = "PENDENTE"
    EM_EXECUCAO = "EM_EXECUCAO"
    AGUARDANDO_CAPTCHA = "AGUARDANDO_CAPTCHA"
    PAUSADA = "PAUSADA"
    SUCESSO = "SUCESSO"
    DUPLICADA = "DUPLICADA"
    IGNORADA = "IGNORADA"
    ERRO = "ERRO"
