from enum import StrEnum


class NotaStatus(StrEnum):
    PENDENTE = "PENDENTE"
    CADASTRANDO = "CADASTRANDO"
    AGUARDANDO_CAPTCHA = "AGUARDANDO_CAPTCHA"
    PAUSADA = "PAUSADA"
    CADASTRADA = "CADASTRADA"
    IGNORADA = "IGNORADA"
    ERRO_CADASTRO = "ERRO_CADASTRO"
